<div class="wow thumbnail">
    <img src="<?php echo $this->thumbnail; ?>" alt="Thumbnail" />
    <div class="caption">
        <h5><?php echo $this->level; ?> <?php echo $this->race; ?> <?php echo $this->class; ?></h5>
    </div>
</div><br>

<h2>Ausrüstung</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Slot</th>
            <th>Ausgerüstet</th>
            <th>Verzauberung</th>
            <th>Verzauberung BiS</th>
            <th>Sockel</th>
            <th>Umgeschmiedet</th>
            <th>BiS</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->gear as $gear): ?>
            <tr>
                <td><?php echo $gear['slot_de']; ?></td>
                <td>
                    <a class="wow item_img q<?php echo $gear['quality']; ?>" rel="<?php echo $gear['url_gems']; ?>&<?php echo $gear['url_enchant']; ?>&<?php echo $gear['url_set']; ?>" href="<?php echo $gear['url']; ?>">
                        <img src="<?php echo $gear['icon_img']; ?>" alt="<?php echo $gear['name']; ?>" />
                        <span><?php echo $gear['name']; ?></span>
                    </a>
                </td>
                <td></td>
                <td></td>
                <td>
                    <?php foreach ($gear['gems'] as $gem): ?>
                    <?php $itemData = $gem->getData(); ?>
                        <a class="" rel="" href="<?php echo $this->wowhead_url; ?>item=<?php echo $itemData['id'] ?>">
                            <img src="<?php echo $gem->getIcon(18); ?>" alt="<?php echo $gem->getName(); ?>" />
                        </a>
                    <?php endforeach; ?>
                </td>
                <td></td>
                <td></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript" src="http://static.wowhead.com/widgets/power.js"></script>