</body>
<script src="view/ressources/js/jquery-1.7.2.min.js"></script>
<script src="view/ressources/js/jquery-ui-1.8.21.custom.min.js"></script>
<script src="view/ressources/js/bootstrap.min.js"></script>
<!--<script src="view/js/jquery.easing-1.3.pack.js"></script>-->
<script src="view/ressources/js/jquery.form.js"></script>
<!--<script src="view/js/jquery.mousewheel-3.0.4.pack.js"></script>-->
<!--<script src="view/js/jquery.tipTip.minified.js"></script>-->
<!--<script src="view/js/tablesorter.js"></script>-->
<script src="view/ressources/js/core.js"></script>
</html>