</body>
<script src="view/js/jquery-ui-bootstrap/js/jquery-1.6.2.min.js"></script>
<script src="view/js/jquery-ui-bootstrap/js/jquery-ui-1.8.16.custom.min.js"></script>
<script src="view/js/jquery-ui-bootstrap/third-party/jQuery-UI-FileInput/js/fileinput.jquery.js"></script>
<script src="view/js/jquery-ui-bootstrap/third-party/jQuery-UI-FileInput/js/enhance.min.js"></script>
<script src="view/js/jquery.easing-1.3.pack.js"></script>
<script src="view/js/jquery.form.js"></script>
<script src="view/js/jquery.mousewheel-3.0.4.pack.js"></script>
<script src="view/js/jquery.tipTip.minified.js"></script>
<script src="view/js/tablesorter.js"></script>
<script src="view/js/core.js"></script>
</html>