<?php require_once('head.phtml'); ?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <?php require_once('mainnav.phtml'); ?>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="content">
            <?php echo $this->content; ?>
        </div><!--/row-->
    </div><!--/row-->
</div><!--/.fluid-container-->
<?php require_once('foot.phtml'); ?>


