<?php
/**
 * wombat
 * 
 * LICENCE
 * 
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to Creative Commons, 
 * 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
 * 
 * @name wombat
 * @author Nico Schmitz - mail@nicoschmitz.eu
 * @copyright  Copyright (c) 2010-2011 Nico Schmitz (mail@nicoschmitz.eu
 * @since 01.04.2010
 * @version 0.1
 * @license http://creativecommons.org/licenses/by-nc-nd/3.0/ Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License
 */
?>
<!DOCTYPE HTML>
<html lang="de">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title><?php echo $this->title ?></title>
        <base href="<?php echo $this->base ?>" />
        <meta name="Author" content="<?php echo $this->author ?>" />
        <meta name="Copyright" content="<?php echo $this->copyright ?>" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        <!--        <link rel="stylesheet" href="view/css/bootstrap.min.css" type="text/css" />-->
        <!--        <link rel="stylesheet" href="view/js/jquery-ui/bootstrap/jquery-ui-1.8.16.custom.css" type="text/css"/>-->
        <!--        <link rel="stylesheet" href="view/js/jquery-ui/bootstrap/jquery-ui-1.8.16.custom.ie.css" type="text/css"/>-->
        <link rel="stylesheet" href="view/js/jquery-ui-bootstrap/third-party/jQuery-UI-FileInput/css/enhanced.css" type="text/css"/>
        <link rel="stylesheet" href="view/js/jquery-ui-bootstrap/css/bootstrap/jquery.ui.1.8.16.ie.css" type="text/css"/>
        <link rel="stylesheet" href="view/js/jquery-ui-bootstrap/css/bootstrap/jquery-ui-1.8.16.custom.css" type="text/css"/>
        <link rel="stylesheet" href="view/js/jquery-ui-bootstrap/bootstrap/bootstrap.css" type="text/css"/>
        <link rel="stylesheet" href="view/css/layout.css" type="text/css"/>
    </head>
    <body>
        <div class="topbar">
            <div class="fill">
                <div class="container">
                    <a class="brand" href="<?php echo $this->base; ?>"><?php echo $this->title; ?></a>
                    <?php require_once('mainnav.phtml'); ?>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="content">
                <div>
                    <?php echo $this->content ?>
                </div>
            </div>
            <footer>
            </footer>
    </body>
    <script src="view/js/jquery-ui-bootstrap/js/jquery-1.6.2.min.js"></script>
    <script src="view/js/jquery-ui-bootstrap/js/jquery-ui-1.8.16.custom.min.js"></script>
    <script src="view/js/jquery-ui-bootstrap/third-party/jQuery-UI-FileInput/js/fileinput.jquery.js"></script>
    <script src="view/js/jquery-ui-bootstrap/third-party/jQuery-UI-FileInput/js/enhance.min.js"></script>
    <script src="view/js/jquery.easing-1.3.pack.js"></script>
    <script src="view/js/jquery.form.js"></script>
    <script src="view/js/jquery.mousewheel-3.0.4.pack.js"></script>
    <script src="view/js/jquery.tipTip.minified.js"></script>
    <script src="view/js/tablesorter.js"></script>
    <script src="view/js/core.js"></script>
</html>

