<?php
/**
 * wombat
 * 
 * LICENCE
 * 
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to Creative Commons, 
 * 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
 * 
 * @name wombat
 * @author Nico Schmitz - mail@nicoschmitz.eu
 * @copyright  Copyright (c) 2010-2011 Nico Schmitz (mail@nicoschmitz.eu
 * @since 01.04.2010
 * @version 0.1
 * @license http://creativecommons.org/licenses/by-nc-nd/3.0/ Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License
 */
?>
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $this->title ?></title>
        <base href="<?php echo $this->base ?>" />
        <meta name="Author" content="<?php echo $this->author ?>" />
        <meta name="Copyright" content="<?php echo $this->copyright ?>" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="view/css/layout.css" type="text/css"/>
        <link rel="stylesheet" href="library/bootstrap-1.0.0.min.css" type="text/css" />
        <link rel="stylesheet" href="library/jquery/fancybox/jquery.fancybox-1.3.4.css"/>
        <link rel="stylesheet" href="library/jquery/jquery-ui/jquery-ui-1.8.16.custom.css"/>
    </head>
    <body>
        <section class="container">
            <nav>
                <div class="topbar-wrapper">
                    <div class="topbar">
                        <div class="container fixed">
                            <h3><a href="" class="logo">wombat</a></h3>
                            <form action="">
                                <input type="text" placeholder="Suche">
                            </form>
                            <ul>
                                <?php foreach ($this->navigation as $item): ?>
                                    <?php if ($item['url'] == $this->active): ?>
                                        <li class="active"><a href="<?php echo $item['url'] ?>" class="movie"><?php echo $item['title'] ?></a></li>
                                    <?php else: ?>
                                        <li><a href="<?php echo $item['url'] ?>" class="awesome blue medium large"><?php echo $item['title'] ?></a></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                            <ul class="nav secondary-nav nav-config">
                                <li class="menu">
                                    <a class="menu menu-config" href="#">Einstellungen</a>
                                    <ul class="menu-dropdown dropdown-config" style="display: none;">
                                        <li><a href="">Allgemein</a></li>
                                        <li><a href="">Benutzer</a></li>
                                        <li><a href="">Format</a></li>
                                        <li><a href="">Bewertungen</a></li>
                                        <li><a href="">Genre</a></li>
                                        <li><a href="">Künstler</a></li>
                                        <li class="divider"></li>
                                        <li><a href="">Another link</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
            <section class="content">
                <?php echo $this->content ?>
            </section>
        </section>
    </body>
    <script src="library/jquery/jquery-1.6.1.min.js"></script>
    <script src="library/jquery/jquery.easing-1.3.pack.js"></script>
    <script src="library/jquery/jquery.form.js"></script>
    <script src="library/jquery/jquery.mousewheel-3.0.4.pack.js"></script>
    <script src="library/jquery/jquery.tipTip.minified.js"></script>
    <script src="library/jquery/jquery.autocomplete.pack.js"></script>
    <script src="library/jquery/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
    <script src="library/jquery/jquery-ui/jquery-ui-1.8.14.custom.min.js"></script>
    <script src="library/jquery/tablesorter.js"></script>
    <script src="js/core.js"></script>
</html>