<a class="brand" href="#">wombat</a>
<div class="nav-collapse">
    <ul class="nav">
        <li class="divider-vertical"></li>
        <li <?php echo ($this->url->getController() == 'dashboard') ? 'class="active"' : ''; ?>>
            <a href="dashboard/">
                <i class="icon-home icon-white"></i> Dashboard
            </a>
        </li>
        <li class="divider-vertical"></li>
        <li <?php echo ($this->url->getController() == 'movie') ? 'class="active"' : ''; ?>>
            <a href="movie/"><i class="icon-film icon-white"></i> Filme</a>
        </li>
        <li class="divider-vertical"></li>
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="icon-cog icon-white"></i> Einstellungen <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#">Benutzer</a></li>
                <li class="divider"></li>
                <li><a href="#">Genre</a></li>
                <li><a href="#">Format</a></li>
                <li><a href="#">Künstler</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#"><i class="icon-cog"></i> Administration</a></li>
            </ul>
        </li>
    </ul>
</div>