<div class="pagination">
    <ul>
        <?php if ($this->paginator->current == $this->paginator->first): ?>
            <li class="prev disabled"><a href="<?php echo $this->url->getController(); ?>/<?php echo $this->url->getAction()?>/page/<?php echo $this->paginator->first; ?>">&larr; erste</a></li>
        <?php else: ?>
            <li class="prev"><?php echo $this->url->getController(); ?>/<?php echo $this->url->getAction()?>/page/<?php echo $this->paginator->first; ?>">&larr; erste</a></li>
        <?php endif; ?>
            <?php foreach ($this->paginator->pagesInRange as $page): ?>
            <?php if($this->paginator->current == $page): ?>
                <li class="active"><?php echo $this->url->getController(); ?>/<?php echo $this->url->getAction()?>/page/<?php echo $page; ?>"><?php echo $page; ?></a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->url->getController(); ?>/<?php echo $this->url->getAction()?>/page/<?php echo $page; ?>"><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach;?>
        <?php if($this->paginator->current == $this->paginator->last): ?>
            <li class="next disabled"><?php echo $this->url->getController(); ?>/<?php echo $this->url->getAction()?>/page/<?php echo $this->paginator->last; ?>">letzte &rarr;</a></li>
        <?php else: ?>
            <li class="next"><a href="<?php echo $this->url->getController(); ?>/<?php echo $this->url->getAction()?>/page/<?php echo $this->paginator->last; ?>">letzte &rarr;</a></li>
        <?php endif; ?>
    </ul>
</div>