<ul class="breadcrumb">
    <form class="form-inline">
        <input type="text" value="" class="span12" placeholder="Bitte Suchbegriff eingeben ..." />
<!--        <button id="search-btn" data-placement="bottom" title="Hinweis" data-content="Die Suche greift immer nur auf den aktuellen Datenbestand zu." class="btn" type="submit">
            <i class="icon-search"></i> Suchen
        </button>-->
<!--        <label for="entriesPerPage">Einträge pro Seite</label>
        <select name="entriesPerPage">
            <option>10</option>
            <option>20</option>
            <option>30</option>
            <option>40</option>
        </select>-->
    </form>
</ul>