<?php
/**
 * wombat
 * 
 * LICENCE
 * 
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to Creative Commons, 
 * 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
 * 
 * @name wombat
 * @author Nico Schmitz - mail@nicoschmitz.eu
 * @copyright  Copyright (c) 2010-2011 Nico Schmitz (mail@nicoschmitz.eu
 * @license http://creativecommons.org/licenses/by-nc-nd/3.0/ Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License
 */
?>
<!DOCTYPE HTML>
<html lang="de">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>wombat <?php echo (!empty($this->page_title)) ? ' - '.$this->page_title : '' ?><?php echo (!empty($this->page_sub_title)) ? ' - '.$this->page_sub_title : '' ?></title>
        <base href="<?php echo $this->base ?>" />
        <meta name="Author" content="Nico Schmitz" />
        <meta name="Copyright" content="2010 - <?php echo date('Y'); ?> Nico Schmitz - mail@nicoschmitz.eu" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        <link href='http://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="public/css/bootstrap.min.css" type="text/css"/>
        <link rel="stylesheet" href="public/css/smoothness/jquery-ui-1.8.21.custom.css" type="text/css"/>
        <link rel="stylesheet" href="public/css/layout.css" type="text/css"/>
    </head>
    <body>