<form class="form-inline toolbar" action="<?php echo $this->url->getUrl(); ?>" method="POST" accept-charset="utf-8">
    <div class="page-header">
        <h1>Filme <small>Übersicht</small></h1>
    </div>
    <ul class="breadcrumb">
        <a class="btn btn-success left margin-10-right" href="<?php echo $this->url->getController(); ?>/add/"><i class="icon-plus-sign icon-white"></i> Hinzufügen</a>
        <input type="text" class="span3 search_value margin-10-right" name="search_value" placeholder="<?php echo (!empty($this->search_value)) ? $this->search_value : 'Bitte Suchbegriff eingeben ...'; ?>" />
        <?php if (!empty($this->search_value)): ?>
            <button type="submit" value="cancel" class="close">&times;</button>
        <?php endif; ?>
        <button id="search-btn" data-placement="bottom" title="Hinweis" class="btn" type="submit">
            <i class="icon-search"></i> Suchen
        </button>
    </ul>
</form>
