<form id="edit" class="form-stacked" method="POST" action="movie/append/" enctype="multipart/form-data" >
    <div class="clearfix">
        <label for="title">Titel</label>
        <div class="input">
            <input type="text" placeholder="Titel" class="span8" name="title"  />
        </div>
    </div>
    <div class="clearfix">
        <label for="format">Format</label>
        <div class="input">
            <select name="format" id="format" class="format span8">
                <?php foreach ($this->format as $format): ?>
                    <option value="<?php echo $format->getId(); ?>"><?php echo $format->getName(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="clearfix">
        <label for="rating">Bewertung</label>
        <div class="input">
            <select name="rating" id="rating" class="span8">
                <?php foreach ($this->rating as $rating): ?>
                    <option value="<?php echo $rating->getId(); ?>"><?php echo $rating->getName(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="clearfix">
        <label for="duration">Länge</label>
        <div class="input">
            <input type="text" name="duration" id="duration" class="span8"  />
        </div>
    </div>
    <div class="clearfix">
        <label for="year">Jahr</label>
        <div class="input">
            <input type="text" name="year" id="year" class="span8" />
        </div>
    </div>
    <div class="clearfix">
        <label for="trailer">Trailer</label>
        <div class="input">
            <input type="text" name="trailer" id="trailer" class="span8"  />
        </div>
    </div>
    <div class="clearfix">
        <label for="description">Beschreibung</label>
        <div class="input">
            <textarea id="description" class="span8" name="description"></textarea>
        </div>
    </div>
    <div class="clearfix">
        <label for="autocompleteGenre">Genre</label>
        <div class="input">
            <input type="text" name="genre" class="span8" id="genre"/>
        </div>
    </div>
    <div class="form-actions">
        <button class="btn btn-primary" type="submit"><i class="icon-ok icon-white"></i> Speichern</button>
        <button class="btn btn-danger" type="submit"><i class="icon-ok icon-white"></i> Löschen</button>
        <a href="movie/" class="btn"><i class="icon-share-alt"></i> Zurück</a>
    </div>
</form>