<div class="page-header">
    <h1>Film <small>Detailansicht</small></h1>
</div>
<div class="movie-container">
    <div class="general-information">
        <p><span>Titel:</span> <?php echo $this->movie->getTitle(); ?></p>
        <p><span>Format:</span> <?php echo $this->movie->getFormat(); ?></p>
        <p><span>Genre:</span> <?php echo $this->movie->getGenre(); ?></p>
        <p><span>Bewertung:</span> <?php echo $this->movie->getRating(); ?></p>
    </div>
    <p class="description"><?php echo $this->movie->getDescription(); ?></p>
</div>
<div class="form-actions">
    <a class="btn btn-primary" href="movie/edit/id/<?php echo $this->movie->getId(); ?>">Bearbeiten</a>
    <a class="btn" href="movie/">Zurück</a>
</div>