<form id="form-entry" class="form-stacked">
    <div class="clearfix">
        <input type="text" placeholder="Benutzername" class="span7" name="username" value="" />
    </div>
    <div class="clearfix">
        <input type="password" placeholder="Passwort" class="span7" name="password" value="" />
    </div>
    <div class="actions clearfix">
        <button class="btn primary" type="submit">Anmelden</button>
    </div>
</form>