<div class="span11">
    <h1>wombat</h1>
    <br>
    <p>Um Zugriff auf die Anwendung zu erhalten, benötigst du ein <em>Benutzerkonto</em>. Dafür kannst du dich einfach registrieren. Jedoch muss dieses
        Benutzerkonto erst von einem Administrator <strong>freigeschaltet</strong> werden.</p>
    <br>
    <form id="form-entry" method="POST" action="user/login/">
        <input type="text" placeholder="Benutzername" class="span11" name="username" value="" />
        <input type="password" placeholder="Passwort" class="span11" name="password" value="" />
        <div class="form-actions">
            <button class="btn btn-large btn-primary" type="submit" name="submit"><i class="icon-ok-sign icon-white"></i> Anmelden</button>
            <a class="btn btn-large" href="user/pw_forgotten/"><i class="icon-info-sign"></i> Passwort vergessen</a>
            <a class="btn btn-large" href="user/register/"><i class="icon-pencil"></i> Registrieren</a>
        </div>
    </form>
</div>

