<div class="hero-unit">
    <h1>wombat</h1>
    <br>
    <p>Um Zugriff auf die Anwendung zu erhalten, benötigst du ein Benutzerkonto. Dafür kannst du dich einfach registrieren. Jedoch muss dieses
        Benutzerkonto erst von einem Administrator <strong>freigeschaltet</strong> werden.</p>
    <br>
    <form id="form-entry" class="">
        <div class="input-prepend">
            <span class="add-on"><i class="icon-user"></i></span>
            <input type="text" placeholder="Benutzername" class="span10" name="username" value="" />
        </div>
        <div class="input-prepend">
            <span class="add-on"><i class="icon-question-sign"></i></span>
            <input type="password" placeholder="Passwort" class="span10" name="password" value="" />
        </div>
        <div class="form-actions">
            <button class="btn btn-large btn-primary" type="submit"><i class="icon-ok-sign icon-white"></i> Anmelden</button>
            <a class="btn btn-large" href="user/pw_forgotten/"><i class="icon-info-sign"></i> Passwort vergessen</a>
            <a class="btn btn-large" href="user/register/"><i class="icon-pencil"></i> Registrieren</a>
        </div>
    </form>
</div>

