<?php echo $this->layout()->head; ?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <?php echo $this->layout()->mainnav; ?>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
<?php echo $this->layout()->foot; ?>