<?php require_once('view/scripts/head.phtml'); ?>
<div id="entry" class="container">
    <div class="topbar">
        <div class="fill">
            <div class="container">
                <ul class="nav">
                    <li><a href="#" class="brand">wombat</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="content">
        <div>
            <?php echo $this->content ?>
        </div>
    </div>
</div>
<?php require_once('view/scripts/foot.phtml'); ?>
